version: '3'
services:
  redis-cache:
    image: redis:7.0-alpine
    env_file:
      - .env
    ports:
      - "${SPRING_REDIS_PORT:-6379}:${SPRING_REDIS_PORT:-6379}"
    networks:
      - message-network
    restart: unless-stopped
    # --save 20 1 instructs the redis server to save the dataset to disk every 20 seconds,
    # if there are one or more writes
    command: redis-server --port ${SPRING_REDIS_PORT:-6379} --save 20 1 --loglevel debug
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis-cache:/data
  
  message-server:
    build:
      context: message-server
      dockerfile: Dockerfile
    image: message-server:latest
    expose:
      - "5555"
    ports:
      - "5555-5560:5555"
    networks:
      - message-network
    restart: unless-stopped
    depends_on:
      - redis-cache
    env_file:
      - .env
    environment:
      JVM_XMS: "${JVM_XMS:-1g}"
      JVM_XMX: "${JVM_XMX:-1g}"
      SERVER_PORT: "${SERVER_PORT:-5555}"
      SPRING_REDIS_HOST: "${SPRING_REDIS_HOST:-redis-cache}"
      SPRING_REDIS_PORT: "${SPRING_REDIS_PORT:-6379}"
      SPRING_REDIS_DATABASE: "${SPRING_REDIS_DATABASE:-0}"
      SPRING_REDIS_TIMEOUT: "${SPRING_REDIS_TIMEOUT:-60000}"
      SPRING_CACHE_TYPE: "${SPRING_CACHE_TYPE:-redis}"
      SPRING_CACHE_REDIS_CACHE_NULL_VALUES: "${SPRING_CACHE_REDIS_CACHE_NULL_VALUES:-false}"
      APP_RATE_LIMIT_MODE: "${APP_RATE_LIMIT_MODE:-auto}"
      APP_OUTPUT_DIR: "${APP_OUTPUT_DIR:-/output/1}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "~/.rate-limiter${APP_OUTPUT_DIR:-/output/1}:${APP_OUTPUT_DIR:-/output/1}"

  nginx:
    image: nginx:latest
    ports:
      - "4444:4444"
    networks:
      - message-network
    restart: unless-stopped
    depends_on:
      - message-server
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - "~/.rate-limiter${APP_OUTPUT_DIR:-/output/1}/logs:/logs"

  message-client:
    build:
      context: message-client
      dockerfile: Dockerfile
    image: message-client:latest
    ports:
      - "3333:3333"
    networks:
      - message-network
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVER_PORT: 3333
      APP_MESSAGE_SERVER_URL: http://nginx:4444
      APP_RATE_LIMIT_MODE: "${APP_RATE_LIMIT_MODE:-auto}"
      APP_OUTPUT_DIR: "${APP_OUTPUT_DIR:-/output/1}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "~/.rate-limiter${APP_OUTPUT_DIR:-/output/1}:${APP_OUTPUT_DIR:-/output/1}"

networks:
  message-network:
    driver: bridge

volumes:
  redis-cache:
    driver: local
