rate-limiter:
  resource-packages: io.github.poshjosh.ratelimiter.tests.server

spring:
  application:
    name: message-server
  cache:
    cache-names: messages-cache
    type: redis
    redis:
      cache-null-values: false
  session:
    store-type: redis

server:
  port: 5555

app:
  rate-limit-mode: auto

debug: false

logging:
  level:
    ROOT: info
    web: info
    io.github.poshjosh: info
    org.springframework: info
#    org.springframework.cache: info
#    org.springframework.data.redis: info
#    org.springframework.data.redis.core: info
#    org.springframework.data.redis.connection: info

