rate-limiter:
  resource-packages: io.github.poshjosh.ratelimiter.tests.server.resources

spring:
  application:
    name: message-server
  cache:
    cache-names: messages-cache
    type: redis
    redis:
      cache-null-values: false
  session:
    store-type: redis

server:
  port: 5555

app:
  output-dir: /.rate-limiter/output
  rate-limit-mode: auto
  rate-limiter:
    service:
      url: "${APP_RATE_LIMITER_SERVICE_URL}"
      # When acquiring permits, we don't want to block the actual request,
      # so we stop the process after some timeout, and proceed with the request.
      timeout-millis: 500

debug: false

logging:
  level:
    ROOT: info
    web: info
    io.github.poshjosh: info
#    io.github.poshjosh.ratelimiter.matcher.MatchVisitors: trace
#    io.github.poshjosh.ratelimiter.matcher.MatchContexts: trace
#    io.github.poshjosh.ratelimiter.matcher.DefaultMatchContext: trace
    org.springframework: info
#    org.springframework.cache: info
#    org.springframework.data.redis: info
#    org.springframework.data.redis.core: info
#    org.springframework.data.redis.connection: info

