spring:
  application:
    name: message-client

server:
  port: 3333

app:
  message-server:
    url: http://localhost:5555
  rate-limit-mode: auto
  output-dir: /.rate-limiter/logs/tests

debug: false

logging:
  level:
    ROOT: INFO
    web: INFO
