spring:
  application:
    name: message-client

server:
  port: 3333

app:
  message-server:
    url: http://localhost:5555
  rate-limit-mode: auto
  output-dir: /.rate-limiter/output

debug: false

logging:
  level:
    ROOT: info
    web: info
    io.github.poshjosh: info
    org.springframework: info
#    org.springframework.cache: info
#    org.springframework.data.redis: info
#    org.springframework.data.redis.core: info
#    org.springframework.data.redis.connection: info
